kind: pipeline
name: default

steps:
  - name: docker
    image: docker
    commands:
      - echo $DOCKER_USERNAME
      - echo $DOCKER_PASSWORD
    secrets: [ DOCKERHUB_USER, DOCKERHUB_PASSWORD ]
  - name: build
    image: maven
    secrets: [ DOCKERHUB_USER, DOCKERHUB_PASSWORD ]
    commands: 
      - mvn clean package
