---
kind: pipeline
name: build

clone:
  depth: 50

steps:
  - name: build
    image: maven
    secrets: [ DOCKERHUB_USERPASSWORD, DOCKERHUB_USER ]
    commands: 
      - mvn clean package -X
    settings:
      environment:  
        DOCKERHUB_USERPASSWORD:
          from_secret: DOCKERHUB_USERPASSWORD
        DOCKERHUB_USER:
          from_secret: DOCKERHUB_USER
    when:
      event:
        - push
