---
kind: pipeline
name: build

clone:
  depth: 50

steps:
  - name: build
    image: maven
    commands: 
      - mvn clean package
    settings:
      environment:  
        DOCKERHUB_PASSWORD:
          from_secret: DOCKERHUB_PASSWORD
        DOCKERHUB_USER:
          from_secret: DOCKERHUB_USER
    when:
      event:
        - push
