kind: pipeline
name: default

steps:
  - name: docker
    image: docker
    commands:
      - echo $$DOCKERHUB_PASSWORD
      - echo $$DOCKERHUB_USER
    secrets: [ DOCKERHUB_USER, DOCKERHUB_PASSWORD ]
  - name: build
    image: maven
    secrets: [ DOCKERHUB_USER, DOCKERHUB_PASSWORD ]
    commands: 
      - mvn clean package
